### ISSUE TITLE
Too much DNS querying

### ISSUE THREAD

**Issue by minaguib** [bvandenbos/statsd-client#1]
The DNS service is queried once per sent packet if the supplied host is a hostname and not an IP address.

Ideally, the hostname is resolved only once (ever, or per configurable X seconds) and the resulting IP address is what's used in sending the UDP packet.

Now that I think of it, I believe (though untested) that if the DNS service is down or slow, the sending of the UDP packet in the current code will block while the resolving library tries to resolve the hostname to an IP address - so the whole benefit of UDP being fire-and-forget is overshadowed by the blocking DNS operation before the sending.

Ideally, DNS resolution (wherever it's done - by statsd-client or lower) is done with an appropriate, configurable timeout - and not done too often.

**Comment by bvandenbos** [comment]
This is a great suggestion.

**Comment by bvandenbos** [comment]
Fixed in 0.0.4.  Does the look up once and caches forever.
