### ISSUE TITLE
Requires rubygems >= 1.3.6 for no apparent reason

### ISSUE THREAD

**Issue by aaronbbrown** [bvandenbos/statsd-client#3]
`gem install statsd-client` requires rubygems >= 1.3.6, but there doesn't seem to be a reason for that dependency.  This prevents people running Ubuntu 10.04 lucid from installing the gem without a --force.

**Comment by bvandenbos** [comment]
Fixed.  Pushed 0.0.6.

Thanks.

**Comment by aaronbbrown** [comment]
Awesome, thanks!

On Tue, Dec 6, 2011 at 12:30 PM, Ben VandenBos <
reply@reply.github.com
