### ISSUE TITLE
Statsd.time block does not exist 

### ISSUE THREAD

**Issue by yopefonic** [bvandenbos/statsd-client#4]
While using the gem to set up statsd for our rails client app I noticed the Statsd.time block method does not exist.

Looking into your code it seems like the documentation is out of sync with the code. The Statsd.timing method can receive a block and do this. Is there any reason the documentation and code are out of sync? is it planned to create the time method or is the use of the timing method the proper use?

**Comment by bvandenbos** [comment]
Nope - typo.  Fixed.  Thanks

**Comment by yopefonic** [comment]
okay, cool.
